### ISSUE TITLE
8021q driver only loads after multiple attempts.

### ISSUE THREAD

**Issue by RikusW** [openil/openil#18]
Every time I try loading the 8021q driver on the LS1021ATSN box the following happens:

[ 1152.896604] 8021q: section 3 reloc 2 sym 'csum_partial': relocation 28 out of range (0xbf000150 -> 0xc102e59c)
[ 1152.938560] 8021q: section 3 reloc 2 sym 'csum_partial': relocation 28 out of range (0xbf00c150 -> 0xc102e59c)
modprobe: can't load module 8021q (kernel/net/8021q/8021q.ko): invalid module format

[ 1153.007093] 8021q: section 3 reloc 2 sym 'csum_partial': relocation 28 out of range (0xbf018150 -> 0xc102e59c)
[ 1153.058579] 8021q: section 3 reloc 2 sym 'csum_partial': relocation 28 out of range (0xbf024150 -> 0xc102e59c)
modprobe: can't load module 8021q (kernel/net/8021q/8021q.ko): invalid module format

[ 1153.117124] 8021q: section 3 reloc 20 sym 'dump_stack': relocation 28 out of range (0xbf0302e8 -> 0xc10315b0)
[ 1153.148648] 8021q: section 3 reloc 137 sym 'snprintf': relocation 28 out of range (0xbf03cf04 -> 0xc1045288)
modprobe: can't load module 8021q (kernel/net/8021q/8021q.ko): invalid module format

[ 1153.207365] 8021q: 802.1Q VLAN Support v1.8

And eventually it loads.

**Comment by vladimiroltean** [comment]
Hi, can you try to add `-mlong-calls` to CFLAGS and recompile the kernel?

**Comment by RikusW** [comment]
Hi, I added ARCH_CFLAGS := -mlong-calls  in the kernel makefile, now it is crashing when init tries to load...  I didn't modify any settings, I used the OpenIL-201810 tag to build as described in OPEN-LINUX-IND-UM-1-3-1.pdf

I'm not sure what the proper way would be to add -mlong-calls to CFLAGS or where to see what toolchain is being used. I'm using Ubuntu 16.04.

**Comment by vladimiroltean** [comment]
As a temporary workaround if `-mlong-calls` doesn't work, you can always compile all your modules as built-in (replace `m` with `y` in the defconfig), until this gets solved.

**Comment by RikusW** [comment]
Sounds much simpler to me, thanks.
