### ISSUE TITLE
USB Terminal interface sometimes doesn't work.

### ISSUE THREAD

**Issue by RikusW** [openil/openil#21]
Hi
Sometimes I get only a > on the USB terminal, pressing Enter just give another > and typing commands seem to have no effect, I can still ssh into the LS1021ATSN box. A reboot normally fix this issue, I suspect it happens after unplugging and reconnecting the USB cable. A reconnect actually just fixed it...

**Comment by vladimiroltean** [comment]
The shell gets thrown off by some escape character sent through the tty when you connect to it. When you see ">" it's expecting a newline.
Press ctrl-d to send a EOF character through serial.

**Comment by RikusW** [comment]
Thanks, will try that next time it happens.

**Comment by RikusW** [comment]
Thanks, its working.

**Comment by RikusW** [comment]
Thanks, its working.
