### ISSUE TITLE
LS1021ATSN Serial port is not recognized

### ISSUE THREAD

**Issue by liu-jeff** [openil/openil#30]
After I programmed sdcard.img into the sd card according to the tutorial, I inserted the sd card into the board, powered it up, and then connected it to the board with a pc. I found that my PC did not recognize the serial port.

**Comment by vladimiroltean** [comment]
What operating system?

**Comment by liu-jeff** [comment]
> What operating system?
openil

**Comment by vladimiroltean** [comment]
I mean on the PC.

**Comment by liu-jeff** [comment]
> I mean on the PC.

win10

**Comment by vladimiroltean** [comment]
Have you installed the ARM mbed serial driver?
https://os.mbed.com/handbook/Windows-serial-configuration

**Comment by vladimiroltean** [comment]
Try another cable then?

**Comment by vladimiroltean** [comment]
Does it work if you reboot Windows with the cable plugged in?

**Comment by liu-jeff** [comment]
> Does it work if you reboot Windows with the cable plugged in?

thank you very much
