### ISSUE TITLE
Can the scheduling model of the output port be changed?

### ISSUE THREAD

**Issue by liu-jeff** [openil/openil#40]
Hello,  Can the scheduling model of the output port be changed? If I want to modify it, what should I do?

**Comment by vladimiroltean** [comment]
What does this mean?

**Comment by liu-jeff** [comment]
> What does this mean?
Can the code in fpga be changed?like  Qbv

**Comment by liu-jeff** [comment]
> What does this mean?

Because the CPU only configures the TSN function and cannot be changed. If I want to change the TSN function, what should I do?

**Comment by vladimiroltean** [comment]
Assuming that you are asking about sja1105, felix or enetc, the silicon implementation is fixed in all cases. There is no FPGA.

**Comment by liu-jeff** [comment]
> Assuming that you are asking about sja1105, felix or enetc, the silicon implementation is fixed in all cases. There is no FPGA or firmware.

I don't quite follow you. I want to know whether the function (like QBV) of ls1021 or ls1028TSN can be modified? Because the kernel only does configuration,You mean it can't change it, it can only configure ?

**Comment by vladimiroltean** [comment]
Please provide a more concrete example by what you mean with change vs configure.

**Comment by liu-jeff** [comment]
> Please provide a more concrete example of what you mean with change vs configure.

For ls1021, the TSN function is in sja1105 chip, but the code in sja1105 cannot be modified. For example, I want to change the number of QBV gates (8 to 9). Can I change it? In fact, I just want to know whether the TSN function of ls1021 or 1028 can be developed again

**Comment by vladimiroltean** [comment]
Ok, see the answer above then.

**Comment by liu-jeff** [comment]
> Ok, see the answer above then. The hardware implementation is fixed.
Ok,thank you very much!
