### ISSUE TITLE
How to change the ip address in LS1021ATSN using openil-community

### ISSUE THREAD

**Issue by sabarishsubramanian** [openil/openil#43]
I have done the initial steps by loading the files in sd card and inserting in the board and booting it and paused it and i got => in the boot loader command.

Now how will proceed to change the ip address?

**Comment by vladimiroltean** [comment]
```
setenv ipaddr 192.168.1.2
setenv serverip 192.168.1.1
ping $serverip
```
Is this what you want? To ping from U-Boot?

**Comment by sabarishsubramanian** [comment]
want to change the MAC addresse and ip address of the  boards by executing these U-boot commands

**Comment by vladimiroltean** [comment]
To change the MAC address, follow the [official U-Boot steps to reprogram the EEPROM ](https://gitlab.denx.de/u-boot/u-boot/tree/master/board/freescale/ls1021atsn)and reboot.

**Comment by sabarishsubramanian** [comment]
its not working 
=> setenv ethaddr  00:04:9f:ef:00:00
=> setenv eth1addr 00:04:9f:ef:01:01
=> setenv eth2addr 00:04:9f:ef:02:02

do i need to use this command for changing ip ?

if yes do i need to change any address of it and wht is that?

**Comment by sabarishsubramanian** [comment]
i got it

 i have another question 

where can i find the network folder or interfaces 

because am not getting in etc folde r when i give 

/etc/network/interfaces 

this command
