### ISSUE TITLE
minicom freezes

### ISSUE THREAD

**Issue by sabarishsubramanian** [openil/openil#45]
hello

when i type  minicom -b 115200 -o -D /dev/ttyACM0

i get

Welcome to minicom 2.7

OPTIONS: I18n 
Compiled on Dec  4 2019, 17:19:54.
Port /dev/ttyACM0, 16:30:08

Press CTRL-A Z for help on special keys

here i cant able to type anythings

help me please

**Comment by vladimiroltean** [comment]
Unplug and replug the board's power?

**Comment by sabarishsubramanian** [comment]
iIs sja1105-tool is a Linux user space application for configuring the SJA1105 TSN switch is the only thing or is there anyother way?
