### ISSUE TITLE
in depth debugging of https://github.com/openil/openil/issues/48#

### ISSUE THREAD

**Issue by sabarishsubramanian** [openil/openil#51]
git fetch origin

+ baca464abacb...358e9b02a1df sja1105-tracepoints           -> origin/sja1105-tracepoints  (forced update)

then i did 

git checkout sja1105-tracepoints
# Rebuild the kernel
make linux-dirclean
make linux

then 
# Go to the board 2 console, prepare it for transferring the new kernel
mkdir /boot
mount /dev/mmcblk0p1 /boot
mv /boot/uImage /boot/uImage.old # save the old kernel image
passwordless-ssh-login # make sure root login to the board works

then 

# Then go back to the computer console and transfer the new kernel through ssh
scp output/images/uImage

then gave reboot to board 2

U-Boot 2019.10-rc3 (Jan 07 2020 - 11:48:27 +0100)

CPU:   Freescale LayerScape LS1021E, Version: 2.0, (0x87081120)
Clock Configuration:
       CPU0(ARMV7):1200 MHz, 
       Bus:300  MHz, DDR:800  MHz (1600 MT/s data rate), 
Reset Configuration Word (RCW):
       00000000: 0608000c 00000000 00000000 00000000
       00000010: 30000000 08007900 40105a00 21046000
       00000020: 00000000 00000000 00000000 10002000                            
       00000030: 20124801 8804b340 00000000 00000000                            
Model: NXP LS1021A-TSN Board                                                    
I2C:   ready                                                                    
DRAM:  1 GiB                                                                    
Using SERDES1 Protocol: 48 (0x30)                                               
MMC:   FSL_SDHC: 0                                                              
Loading Environment from MMC... OK                                              
EEPROM: Invalid ID (ff ff ff ff)                                                
In:    serial                                                                   
Out:   serial                                                                   
Err:   serial                                                                   
SEC0: RNG instantiated                                                          
SCSI:                                                                           
Net:   eth0: ethernet@2d10000 [PRIME], eth1: ethernet@2d50000                   
Hit any key to stop autoboot:  0                                                
switch to partitions #0, OK                                                     
mmc0 is current device                                                          
Scanning mmc 0:1...                                                             
Found /extlinux/extlinux.conf                                                   
Retrieving file: /extlinux/extlinux.conf                                        
160 bytes read in 30 ms (4.9 KiB/s)                                             
1:      OpenIL 1.6-community - NXP LS1021A-TSN                                  
Retrieving file: /extlinux/../uImage                                            
Skipping OpenIL 1.6-community - NXP LS1021A-TSN for failure retrieving kernel   
SCRIPT FAILED: continuing...                                                    
Scanning mmc 0:2...                                                             
starting USB...                                                                 
Bus usb3@3100000: Register 200017f NbrPorts 2                                   
Starting the controller                                                         
USB XHCI 1.00                                                                   
scanning bus usb3@3100000 for devices... 3 USB Device(s) found                  
       scanning usb for storage devices... 0 Storage Device(s) found            
                                                                                
Device 0: unknown device                                                        
PCIe0: pcie@3400000 Root Complex: no link                                       
PCIe1: pcie@3500000 disabled                                                    
ethernet@2d10000 Waiting for PHY auto negotiation to complete......... TIMEOUT !
Could not initialize PHY ethernet@2d10000                                       
Speed: 1000, full duplex                                                        
BOOTP broadcast 1                                                               
BOOTP broadcast 2                                                               
BOOTP broadcast 3                                                               
BOOTP broadcast 4                                                               
BOOTP broadcast 5                                                               
BOOTP broadcast 6                                                               
BOOTP broadcast 7                                                               
BOOTP broadcast 8                                                               
BOOTP broadcast 9                                                               
BOOTP broadcast 10                                                              
BOOTP broadcast 11                                                              
BOOTP broadcast 12                                                              
BOOTP broadcast 13                                                              
BOOTP broadcast 14                                                              
BOOTP broadcast 15                                                              
BOOTP broadcast 16                                                              
BOOTP broadcast 17                                                              
                                                                                
Retry time exceeded; starting again                                             
Speed: 1000, full duplex                                                        
BOOTP broadcast 1                                                               
BOOTP broadcast 2                                                               
BOOTP broadcast 3                                                               
BOOTP broadcast 4                                                               
BOOTP broadcast 5                                                               
BOOTP broadcast 6                                                               
BOOTP broadcast 7                                                               
BOOTP broadcast 8                                                               
BOOTP broadcast 9                                                               
BOOTP broadcast 10                                                              
BOOTP broadcast 11                                                              
BOOTP broadcast 12                                                              
BOOTP broadcast 13                                                              
BOOTP broadcast 14                                                              
BOOTP broadcast 15                                                              
BOOTP broadcast 16                                                              
BOOTP broadcast 17                                                              
                                                                                
Retry time exceeded; starting again                                             
Trying load from qspi..                                                         
SF: Detected s25fl256s1 with page size 256 Bytes, erase size 64 KiB, total 32 MB
Offset exceeds device limit                                                     
sf - SPI flash sub-system                                                       
                                                                                
Usage:                                                                          
sf probe [[bus:]cs] [hz] [mode] - init flash device on given SPI bus            
                                  and chip select                               
sf read addr offset|partition len       - read `len' bytes starting at          
                                          `offset' or from start of mtd         
                                          `partition'to memory at `addr'        
sf write addr offset|partition len      - write `len' bytes from memory         
                                          at `addr' to flash at `offset'        
                                          or to start of mtd `partition'        
sf erase offset|partition [+]len        - erase `len' bytes from `offset'       
                                          or from start of mtd `partition'      
                                         `+len' round up `len' to block size    
sf update addr offset|partition len     - erase and write `len' bytes from memoy
                                          at `addr' to flash at `offset'        
                                          or to start of mtd `partition'        
sf protect lock/unlock sector len       - protect/unprotect 'len' bytes starting
                                          at address 'sector'                   
                                                                                
Wrong Image Format for bootm command                                            
ERROR: can't get kernel image!                                                  
=> 

didnt do the nxt steps later is this right what am doing?

**Comment by vladimiroltean** [comment]
Please send me an email (I don't have yours), don't open another thread.
