### ISSUE TITLE
When will openil give  support for tsn 802.1qcc?

### ISSUE THREAD

**Issue by nwpucong** [openil/openil#55]

**Comment by vladimiroltean** [comment]
IEEE 802.1Qcc contains a large assortment of amendments to 802.1Q-2018, for MRP, MMRP, bridge management, the MIB, FQTSS, as well as an entirely new clause "46. Time-Sensitive Networking (TSN) configuration" which goes over 3 distinct configuration models (fully distributed, centralized network/distributed user, fully centralized). What it is from this standard that you would like to see?
